version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres3
    environment:
      POSTGRES_DB: casbin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-networks

  api-service:
    build: .
    container_name: api-service
    ports:
      - "8080:8080"
    networks:
      - app-networks
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./casbin:/app/casbin
    depends_on:
      - postgres

volumes:
  db:

networks:
  app-networks:
    driver: bridge

